# fly.toml app configuration file generated for alaria-wiki on 2025-04-22T15:21:57-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alaria-wiki'
primary_region = 'sea'

[build]
  image = "ghcr.io/thijmengthn/wiki:latest"

[env]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "alaria_wiki_data"
  destination = "/app/database"
